version: '3.8'

services:
  # MySQL Database
  wordpress-db:
    image: mysql:8.0
    container_name: heiwa-wordpress-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - wordpress_db_data:/var/lib/mysql
    networks:
      - wordpress-network

  # WordPress Site
  wordpress:
    image: wordpress:latest
    container_name: heiwa-wordpress-site
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress-plugin:/var/www/html/wp-content/plugins
    depends_on:
      - wordpress-db
    networks:
      - wordpress-network

  # phpMyAdmin (optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: heiwa-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: wordpress-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - wordpress-db
    networks:
      - wordpress-network

volumes:
  wordpress_data:
  wordpress_db_data:

networks:
  wordpress-network:
    driver: bridge
