openapi: 3.0.3
info:
  title: Create Checkout API
  description: Stripe checkout session creation with booking state management
  version: 1.0.0

servers:
  - url: https://your-project.supabase.co/functions/v1
    description: Supabase Edge Function

paths:
  /create-checkout:
    post:
      summary: Create Stripe checkout session and booking draft
      description: Initiates payment flow by creating Stripe session and draft booking record
      operationId: createCheckout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customer_info
                - booking_details
                - pricing_quote
                - success_url
                - cancel_url
              properties:
                customer_info:
                  type: object
                  required:
                    - email
                    - first_name
                    - last_name
                    - phone
                  properties:
                    email:
                      type: string
                      format: email
                    first_name:
                      type: string
                      minLength: 1
                      maxLength: 100
                    last_name:
                      type: string
                      minLength: 1
                      maxLength: 100
                    phone:
                      type: string
                      pattern: '^\+?[1-9]\d{1,14}$'
                    date_of_birth:
                      type: string
                      format: date
                    emergency_contact:
                      type: object
                      required:
                        - name
                        - phone
                      properties:
                        name:
                          type: string
                        phone:
                          type: string
                        relationship:
                          type: string
                booking_details:
                  type: object
                  required:
                    - camp_week_id
                    - beds
                    - check_in_date
                    - check_out_date
                    - guest_count
                  properties:
                    camp_week_id:
                      type: string
                      format: uuid
                    beds:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        format: uuid
                    addons:
                      type: array
                      items:
                        type: object
                        required:
                          - addon_id
                          - quantity
                        properties:
                          addon_id:
                            type: string
                            format: uuid
                          quantity:
                            type: integer
                            minimum: 1
                    special_requests:
                      type: string
                      maxLength: 1000
                pricing_quote:
                  type: object
                  required:
                    - quote_id
                    - total_amount
                    - currency
                  properties:
                    quote_id:
                      type: string
                      format: uuid
                      description: Reference to validated price quote
                    total_amount:
                      type: number
                      format: decimal
                      minimum: 0.01
                    currency:
                      type: string
                      default: "USD"
                    promo_code:
                      type: string
                success_url:
                  type: string
                  format: uri
                  description: Redirect URL after successful payment
                cancel_url:
                  type: string
                  format: uri
                  description: Redirect URL after cancelled payment
      responses:
        '200':
          description: Checkout session created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - checkout_session
                  - booking_draft
                  - expires_at
                properties:
                  checkout_session:
                    type: object
                    required:
                      - id
                      - url
                      - payment_status
                    properties:
                      id:
                        type: string
                        description: Stripe checkout session ID
                      url:
                        type: string
                        format: uri
                        description: Stripe-hosted checkout page URL
                      payment_status:
                        type: string
                        enum: [unpaid, paid, no_payment_required]
                  booking_draft:
                    type: object
                    required:
                      - id
                      - status
                      - customer_id
                      - total_amount
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: Draft booking record ID
                      status:
                        type: string
                        enum: [draft]
                      customer_id:
                        type: string
                        format: uuid
                      total_amount:
                        type: number
                        format: decimal
                      expires_at:
                        type: string
                        format: date-time
                        description: When draft expires if not paid
                  expires_at:
                    type: string
                    format: date-time
                    description: Session expiration time
        '400':
          description: Invalid request or unavailable inventory
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                properties:
                  error:
                    type: string
                    enum: [VALIDATION_ERROR, INVENTORY_CONFLICT, QUOTE_EXPIRED]
                  message:
                    type: string
        '429':
          description: Rate limited
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                  - retry_after
                properties:
                  error:
                    type: string
                    enum: [RATE_LIMITED]
                  message:
                    type: string
                  retry_after:
                    type: integer
                    description: Seconds to wait before retrying
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                properties:
                  error:
                    type: string
                    enum: [SERVER_ERROR, STRIPE_ERROR]
                  message:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Supabase anon key for checkout creation

security:
  - bearerAuth: []
