'use client'

import { useEffect } from 'react'
import Script from 'next/script'

export default function WidgetDemoPage() {
  useEffect(() => {
    // Configure API for the widget - using REST proxy approach
    if (typeof window !== 'undefined') {
      (window as any).heiwa_booking_ajax = {
        rest_base: `${window.location.origin}/wp-json/heiwa/v1`,
        nonce: 'test_nonce_12345', // In production, this would be generated by WP
        build_id: '20250911-01'
      }
    }
  }, [])

  return (
    <>
      {/* Load jQuery */}
      <Script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        strategy="beforeInteractive"
      />

      {/* Load widget styles */}
      <link
        rel="stylesheet"
        href="/wordpress-plugin/heiwa-booking-widget/assets/css/widget.css?v=2025091204"
      />


      {/* Hard overrides to enforce Heiwa orange theme regardless of plugin CSS order */}
      <style jsx global>{`
        .heiwa-booking-widget .heiwa-booking-step-number {
          background: linear-gradient(135deg, #ec681c, #ed5600) !important;
          color: #fff !important;
          box-shadow: 0 4px 12px rgba(236,104,28,0.30) !important;
        }
        .heiwa-booking-widget .heiwa-booking-step.current .heiwa-booking-step-number,
        .heiwa-booking-widget .heiwa-booking-step.completed .heiwa-booking-step-number {
          background: linear-gradient(135deg, #ec681c, #ed5600) !important;
          color: #fff !important;
          box-shadow: 0 4px 12px rgba(236,104,28,0.30) !important;
        }
        .heiwa-booking-widget .heiwa-booking-summary .heiwa-summary-total .heiwa-summary-total-value {
          background: linear-gradient(135deg, #ec681c, #ed5600) !important;
          -webkit-text-fill-color: transparent !important;
          background-clip: text !important;
        }
        .heiwa-booking-widget .heiwa-modal-header,
        .heiwa-booking-widget .heiwa-booking-inline-header {
          background: linear-gradient(135deg, #ec681c, #ed5600) !important;
          color: #fff !important;
          box-shadow: 0 8px 32px rgba(236,104,28,0.25) !important;
        }
        .heiwa-booking-widget .heiwa-wave-pattern-1,
        .heiwa-booking-widget .heiwa-wave-pattern-2 {
          background-image: none !important;
        }
      `}</style>

      {/* Additional hard overrides for CTAs and focus states */}
      <style jsx global>{`
        .heiwa-booking-widget .heiwa-cta-button,
        .heiwa-booking-widget [data-action="next-step"],
        .heiwa-booking-widget .heiwa-button-primary {
          background: linear-gradient(135deg, #ec681c, #ed5600) !important;
          border-color: #ed5600 !important;
          color: #fff !important;
          box-shadow: 0 6px 18px rgba(236,104,28,0.35) !important;
        }
        .heiwa-booking-widget .heiwa-cta-button:hover,
        .heiwa-booking-widget [data-action="next-step"]:hover {
          filter: brightness(0.98) !important;
          transform: translateY(-1px) !important;
        }
        .heiwa-booking-widget .heiwa-form-input:focus,
        .heiwa-booking-widget .heiwa-select:focus,
        .heiwa-booking-widget .heiwa-date-input:focus {
          outline: none !important;
          box-shadow: 0 0 0 3px rgba(236,104,28,0.25) !important;
          border-color: #ec681c !important;
        }
        .heiwa-booking-widget .heiwa-booking-option-card:hover,
        .heiwa-booking-widget .heiwa-booking-option-card.selected {
          border-color: #ec681c !important;
          box-shadow: 0 10px 30px rgba(236,104,28,0.15) !important;
        }
      `}</style>


      {/* Load widget scripts */}
      <Script
        src="/wordpress-plugin/heiwa-booking-widget/assets/js/widget.js?v=2025091204"
        strategy="afterInteractive"
        onLoad={() => {
          // Auto-initialize widget after script loads
          try {
            setTimeout(() => {
              if (typeof (window as any).HeiwaBookingWidget !== 'undefined') {
                (window as any).HeiwaBookingWidget.init()
              }
            }, 300)
          } catch (e) {
            console.error('HeiwaBookingWidget init failed:', e)
          }
        }}
      />

      {/* Heiwa House Style CSS */}
      <style jsx global>{`
        @import url('https://fonts.googleapis.com/css2?family=Archivo:wght@200;300;400;500;600;700;800;900&family=Archivo+Narrow:wght@400;500;600;700&display=swap');

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: 'Archivo', sans-serif;
          font-size: 18px;
          font-weight: 400;
          line-height: 1.5;
          color: #5a5a5a;
          background-color: #ffffff;
        }

        h1, h2, h3, h4, h5, h6 {
          font-family: 'Archivo Narrow', sans-serif;
          font-weight: 400;
          line-height: 1.2;
          color: #1a1a1a;
        }

        h1 { font-size: 64px; }
        h2 { font-size: 48px; }
        h3 { font-size: 36px; }
        h4 { font-size: 28px; }
        h5 { font-size: 22px; }
        h6 { font-size: 18px; }

        .accent-color { color: #ec681c; }
        .accent-bg { background-color: #ec681c; }

        .btn-primary {
          background-color: #ec681c;
          color: white;
          border: none;
          padding: 11px 32px;
          border-radius: 3px;
          font-size: 15px;
          font-weight: 500;
          text-transform: uppercase;
          letter-spacing: 1px;
          cursor: pointer;
          transition: all 0.3s ease;
          text-decoration: none;
          display: inline-block;
        }

        .btn-primary:hover {
          background-color: #ed5600;
          transform: translateY(-2px);
        }

        .btn-outline {
          background: transparent;
          color: #1a1a1a;
          border: 1px solid #1a1a1a;
          padding: 11px 32px;
          border-radius: 3px;
          font-size: 15px;
          font-weight: 500;
          text-transform: uppercase;
          letter-spacing: 1px;
          cursor: pointer;
          transition: all 0.3s ease;
          text-decoration: none;
          display: inline-block;
        }

        .btn-outline:hover {
          background-color: #ec681c;
          border-color: #ec681c;
          color: white;
        }

        .container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 20px;
        }

        .section {
          padding: 80px 0;
        }

        .section-sm {
          padding: 60px 0;
        }

        .text-center { text-align: center; }
        .text-left { text-align: left; }
        .text-right { text-align: right; }

        .mb-4 { margin-bottom: 2rem; }
        .mb-6 { margin-bottom: 3rem; }
        .mt-4 { margin-top: 2rem; }
        .mt-6 { margin-top: 3rem; }

        .grid {
          display: grid;
          gap: 2rem;
        }

        .grid-2 { grid-template-columns: repeat(2, 1fr); }
        .grid-3 { grid-template-columns: repeat(3, 1fr); }
        .grid-4 { grid-template-columns: repeat(4, 1fr); }

        /* Fixed Position Button Styling */
        .heiwa-booking-widget.heiwa-position-right {
          position: fixed;
          right: 30px;
          top: 50%;
          transform: translateY(-50%);
          z-index: 9999;
        }

        .heiwa-booking-trigger {
          background: #ec681c;
          color: white;
          border: none;
          padding: 15px 20px;
          border-radius: 3px;
          font-family: 'Archivo', sans-serif;
          font-size: 15px;
          font-weight: 500;
          text-transform: uppercase;
          letter-spacing: 1px;
          cursor: pointer;
          transition: all 0.3s ease;
          box-shadow: 0 4px 15px rgba(236, 104, 28, 0.3);
          display: flex;
          align-items: center;
          gap: 8px;
          writing-mode: vertical-rl;
          text-orientation: mixed;
        }

        .heiwa-booking-trigger:hover {
          background: #ed5600;
          transform: translateX(-3px);
          box-shadow: 0 6px 20px rgba(236, 104, 28, 0.4);
        }

        .heiwa-booking-trigger svg {
          transform: rotate(90deg);
        }

        /* Demo Page Styling */
        .heiwa-demo {
          background-color: #ffffff;
          min-height: 100vh;
        }

        .hero-section {
          position: relative;
          height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
          background: linear-gradient(135deg, rgba(26, 26, 26, 0.8), rgba(236, 104, 28, 0.3)),
                      url('https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80');
          background-size: cover;
          background-position: center;
          color: white;
          text-align: center;
        }

        .hero-content h1 {
          font-size: 64px;
          margin-bottom: 20px;
          text-shadow: 2px 2px 4px rgba(0,0,0,0.5);
        }

        .hero-content p {
          font-size: 20px;
          margin-bottom: 40px;
          opacity: 0.9;
        }

        .hero-buttons {
          display: flex;
          gap: 20px;
          justify-content: center;
          flex-wrap: wrap;
        }

        .feature-card {
          background: white;
          padding: 40px 30px;
          border-radius: 8px;
          text-align: center;
          box-shadow: 0 4px 20px rgba(0,0,0,0.1);
          transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

        .feature-card:hover {
          transform: translateY(-5px);
          box-shadow: 0 8px 30px rgba(0,0,0,0.15);
        }

        .feature-icon {
          font-size: 3rem;
          margin-bottom: 20px;
          display: block;
        }

        .feature-card h3 {
          color: #1a1a1a;
          margin-bottom: 15px;
        }

        .feature-card p {
          color: #5a5a5a;
          line-height: 1.6;
        }

        .demo-section {
          background: #f8f9fa;
          padding: 80px 0;
        }

        .demo-content {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 60px;
          align-items: center;
        }

        .demo-features {
          list-style: none;
          padding: 0;
          margin: 20px 0;
        }

        .demo-features li {
          padding: 8px 0;
          color: #5a5a5a;
        }

        .demo-mockup {
          background: white;
          border-radius: 20px;
          padding: 20px;
          box-shadow: 0 20px 60px rgba(0,0,0,0.1);
          max-width: 400px;
          margin: 0 auto;
        }

        .mockup-screen {
          background: #f8f9fa;
          border-radius: 15px;
          overflow: hidden;
        }

        .mockup-header {
          background: #e9ecef;
          padding: 15px;
          display: flex;
          align-items: center;
        }

        .mockup-dots {
          display: flex;
          gap: 8px;
        }

        .mockup-dots span {
          width: 12px;
          height: 12px;
          border-radius: 50%;
          background: #dee2e6;
        }

        .mockup-dots span:first-child { background: #ff5f56; }
        .mockup-dots span:nth-child(2) { background: #ffbd2e; }
        .mockup-dots span:nth-child(3) { background: #27ca3f; }

        .mockup-content {
          padding: 30px 20px;
        }

        .mockup-step {
          background: #e9ecef;
          padding: 12px 16px;
          margin-bottom: 10px;
          border-radius: 8px;
          color: #6c757d;
          font-size: 14px;
        }

        .mockup-step.active {
          background: #ec681c;
          color: white;
        }

        .integration-section {
          background: white;
        }

        .integration-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 30px;
          margin-top: 40px;
        }

        .integration-card {
          background: #f8f9fa;
          padding: 30px;
          border-radius: 8px;
          text-align: center;
        }

        .integration-card h3 {
          color: #1a1a1a;
          margin-bottom: 15px;
        }

        .integration-card p {
          color: #5a5a5a;
          margin-bottom: 20px;
        }

        .integration-card code {
          background: #ec681c;
          color: white;
          padding: 8px 16px;
          border-radius: 4px;
          font-size: 14px;
        }

        @media (max-width: 768px) {
          .heiwa-booking-widget.heiwa-position-right {
            right: 20px;
            bottom: 20px;
            top: auto;
            transform: none;
          }

          .heiwa-booking-trigger {
            writing-mode: horizontal-tb;
            text-orientation: initial;
            padding: 12px 16px;
            font-size: 14px;
          }

          .heiwa-booking-trigger svg {
            transform: none;
          }

          .grid-2, .grid-3, .grid-4 {
            grid-template-columns: 1fr;
          }

          h1 { font-size: 42px; }
          h2 { font-size: 36px; }
          h3 { font-size: 28px; }

          .section { padding: 60px 0; }
          .section-sm { padding: 40px 0; }

          .hero-content h1 { font-size: 42px; }
          .demo-content { grid-template-columns: 1fr; gap: 40px; }
          .integration-grid { grid-template-columns: 1fr; }
          .hero-buttons { flex-direction: column; align-items: center; }
        }
      `}</style>

      {/* Fixed Position Trigger Button - Heiwa House Style */}
      <div className="heiwa-booking-widget heiwa-position-right">
        <button className="heiwa-booking-trigger">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M19 3H5C3.89543 3 3 3.89543 3 5V19C3 20.1046 3.89543 21 5 21H19C20.1046 21 21 20.1046 21 19V5C21 3.89543 20.1046 3 19 3Z" stroke="currentColor" strokeWidth="2"/>
            <path d="M16 2V6" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
            <path d="M8 2V6" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
            <path d="M3 10H21" stroke="currentColor" strokeWidth="2"/>
            <path d="M8 14H16" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
          </svg>
          <span>BOOK NOW</span>
        </button>
      </div>

      <div className="heiwa-demo">

        {/* Hero Section */}
        <section className="hero-section">
          <div className="container">
            <div className="hero-content">
              <h1>Heiwa House Booking Widget</h1>
              <p>Experience our premium surf camp booking system in action</p>
              <div className="hero-buttons">
                <button
                  className="btn-primary"
                  onClick={() => {
                    const trigger = document.querySelector('.heiwa-booking-trigger') as HTMLElement | null;
                    if (trigger) trigger.click();
                  }}
                >
                  Book Your Adventure
                </button>
                <a href="#features" className="btn-outline">Learn More</a>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="section">
          <div className="container">
            <div className="text-center mb-6">
              <h2>Premium Booking Experience</h2>
              <p>Discover the features that make our booking widget exceptional</p>
            </div>

            <div className="grid grid-3">
              <div className="feature-card">
                <div className="feature-icon">🌊</div>
                <h3>Surf-Themed Design</h3>
                <p>Beautiful ocean-inspired interface with wave patterns and premium styling</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">📱</div>
                <h3>Mobile Perfect</h3>
                <p>Flawless experience across all devices with responsive design</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">🏄‍♂️</div>
                <h3>Surf Weeks</h3>
                <p>Complete surf camp booking with skill levels and destinations</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">🏠</div>
                <h3>Room Booking</h3>
                <p>Real-time availability for authentic Heiwa House accommodations</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">⚡</div>
                <h3>Lightning Fast</h3>
                <p>Optimized performance with smooth animations and quick loading</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">🔒</div>
                <h3>Secure & Safe</h3>
                <p>Enterprise-grade security with data protection and validation</p>
              </div>
            </div>
          </div>
        </section>

        {/* Demo Section */}
        <section className="section demo-section">
          <div className="container">
            <div className="demo-content">
              <div className="demo-text">
                <h2>Try the Widget Now</h2>
                <p>Experience the complete booking flow with our interactive demo. Test both surf week packages and room reservations.</p>
                <ul className="demo-features">
                  <li>✅ 8-step guided booking process</li>
                  <li>✅ Real surf camp data integration</li>
                  <li>✅ Dynamic pricing and availability</li>
                  <li>✅ Mobile-optimized interface</li>
                  <li>✅ Accessibility compliant</li>
                </ul>
                <button
                  className="btn-primary mt-4"
                  onClick={() => {
                    const trigger = document.querySelector('.heiwa-booking-trigger') as HTMLElement | null;
                    if (trigger) trigger.click();
                  }}
                >
                  Start Booking Demo
                </button>
              </div>
              <div className="demo-image">
                <div className="demo-mockup">
                  <div className="mockup-screen">
                    <div className="mockup-header">
                      <div className="mockup-dots">
                        <span></span>
                        <span></span>
                        <span></span>
                      </div>
                    </div>
                    <div className="mockup-content">
                      <div className="mockup-step">Step 1: Choose Type</div>
                      <div className="mockup-step">Step 2: Select Dates</div>
                      <div className="mockup-step">Step 3: Add Details</div>
                      <div className="mockup-step active">Step 4: Confirm</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Integration Section */}
        <section className="section integration-section">
          <div className="container">
            <div className="text-center mb-6">
              <h2>WordPress Integration Ready</h2>
              <p>Deploy this widget on any WordPress site with our easy-to-use plugin</p>
            </div>

            <div className="integration-grid">
              <div className="integration-card">
                <h3>Simple Installation</h3>
                <p>Upload the plugin and activate with one click</p>
                <code>[heiwa_booking]</code>
              </div>
              <div className="integration-card">
                <h3>API Connected</h3>
                <p>Real-time data from Heiwa House booking system</p>
                <code>REST API Ready</code>
              </div>
              <div className="integration-card">
                <h3>Customizable</h3>
                <p>Match your brand colors and styling preferences</p>
                <code>CSS Variables</code>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  )
}
